add component
Rostyslav-Zahorulko/planner-frontend pull request #19
Opened 2021-06-28 13:48 UTC by Oksana-Cherry

Компоненты кнопок  и компонент  спринтов, мобильная версия.

2021-06-28 19:11 UTC, Rostyslav-Zahorulko requested changes

2021-06-28 19:11 UTC, Rostyslav-Zahorulko commented on src/App.js
> +import ProdjectPage from './pages/ProjectPage/ProdjectPage.js';
Треба зробити файл `index.js` для реекспорту файлу `ProjectPage.js`.
Тоді імпорт матиме вигляд - `import ProjectPage from './pages/ProjectPage`.

2021-06-28 19:11 UTC, Rostyslav-Zahorulko commented on src/App.js
> +import ProdjectPage from './pages/ProjectPage/ProdjectPage.js';
Файл має називатися `ProjectPage.js`, не `ProdjectPage.js`.

2021-06-28 19:11 UTC, Rostyslav-Zahorulko commented on src/components/Button/AddIconButton/AddIconButton.js
> +import React from 'react';
Компоненти кнопок слід називати за їхнім функціоналом: кнопка додавання - `AddButton`, кнопка видалення - `DeleteButton`, кнопка редагування - `EditButton` тощо. На кожну кнопку - своя папка з файлом js, стилями і файлом реекспорту. Загальна папка `Button` - непотрібна.
Слід переназвати: компонент - на `AddButton`, файл - на `AddButton.js` і перенести їх у папку `src/components/AddButton`.

2021-06-28 19:11 UTC, Rostyslav-Zahorulko commented on src/components/Button/AddIconButton/AddIconButton.module.css
> +.iconButton {
Переназви файл на `AddButton.module.css` і перенеси його в папку `src/components/AddButton`.

2021-06-28 19:11 UTC, Rostyslav-Zahorulko commented on src/components/Button/AddIconButton/index.js
> +export { default } from './AddIconButton';
Слід перенести у папку `src/components/AddButton`.

2021-06-28 19:11 UTC, Rostyslav-Zahorulko commented on src/components/Button/BasketButton/BasketButton.js
> +import React from 'react';
Зауваження аналогічні до висловлених попередньо: переназвати і перемістити. Якщо це кнопка видалення, як я припускаю, то назви її `DeleteButton` або `RemoveButton`.

2021-06-28 19:11 UTC, Rostyslav-Zahorulko commented on src/components/Button/BasketButton/BasketButton.module.css
> +.basket_button {
Переназвати і перемістити.

2021-06-28 19:11 UTC, Rostyslav-Zahorulko commented on src/components/Button/BasketButton/index.js
> +export { default } from './BasketButton';
Перемістити.

2021-06-28 19:11 UTC, Rostyslav-Zahorulko commented on src/components/Button/СhangeButton/ChangeButton.js
> +import React from 'react';
Все те ж саме: переназвати (компонент і файл), перемістити.

2021-06-28 19:11 UTC, Rostyslav-Zahorulko commented on src/components/Button/СhangeButton/ChangeButton.js
> +  <div className={styles.chenge_button}>
Знову цей загадковий `div`.

2021-06-28 19:11 UTC, Rostyslav-Zahorulko commented on src/components/Button/СhangeButton/ChangeButton.module.css
> +.chenge_button {
Переназвати і перемістити.

2021-06-28 19:11 UTC, Rostyslav-Zahorulko commented on src/components/Button/СhangeButton/index.js
> +export { default } from './ChangeButton';
Перемістити.

2021-06-28 19:11 UTC, Rostyslav-Zahorulko commented on src/components/Sprints/SprintItem.js
> +import React from 'react';
На кожен компонент - своя папка в папці `components.` Якщо це компонент спринта, то і лежати його файли повинні у папці компонента спринта. Файли компонена списка спринтів - у папці компонента списка спринтів.
Компонент списка має називатися `SprintsList`.  Його файли (`SprintsList.js`, `SprintsList.module.css` і `index.js`) мають лежати за адресою - `src/components/SprintsList`.
Компонент елемента списка має називатися `SprintsListItem`.  Його файли (`SprintsListItem.js`, `SprintsListItem.module.css` і `index.js`) мають лежати за адресою - `src/components/SprintsListItem`.

2021-06-28 19:11 UTC, Rostyslav-Zahorulko commented on src/components/Sprints/Sprint.module.css
> +@media screen and (min-width: 320px) {
Дивись наступне зауваження.
Якщо коротко: переназвати і перемістити.

2021-06-28 19:11 UTC, Rostyslav-Zahorulko commented on src/components/Sprints/SprintsList.js
> +  <>
Навіщо тут фрагмент?

2021-06-28 19:11 UTC, Rostyslav-Zahorulko commented on src/components/Sprints/SprintsList.js
> +import React from 'react';
Переназвати і перемістити.

2021-06-28 19:11 UTC, Rostyslav-Zahorulko commented on src/pages/ProjectPage/Porodject.module.css
> +.porodject_tital {
`.project-title`

2021-06-28 19:11 UTC, Rostyslav-Zahorulko commented on src/pages/ProjectPage/Porodject.module.css
> +.tital {
`.title`

2021-06-28 19:11 UTC, Rostyslav-Zahorulko commented on src/pages/ProjectPage/Porodject.module.css
> +.porodject_desc {
`.project_desc`

2021-06-28 19:11 UTC, Rostyslav-Zahorulko commented on src/pages/ProjectPage/Porodject.module.css
> +.porodject {
`.project`

2021-06-28 19:11 UTC, Rostyslav-Zahorulko commented on src/pages/ProjectPage/ProdjectPage.js.js
> +const prodjects = [
`projects`

2021-06-28 19:11 UTC, Rostyslav-Zahorulko commented on src/pages/ProjectPage/ProdjectPage.js.js
> +import SprintList from '../../components/Sprints/SprintsList';
Помилка в назві файлу `Pro**d**jectPage.js.**js**`.
Ми вирішили, що тепер це компонент не `ProjectPage`, а `SprintsPage`. Тому переназви сам компонент, його js (на `SprintsPage.js`) і css (на `SprintsPage.module.css`) файли. Створи файл `index.js` для реекспорту.

2021-06-28 19:11 UTC, Rostyslav-Zahorulko commented on src/pages/ProjectPage/Porodject.module.css
> +.porodject {
Дивись наступний коментар. Загалом треба переназвати файл і перемістити його.

2021-06-28 20:00 UTC, Oksana-Cherry commented on src/components/Button/AddIconButton/AddIconButton.js
> +import React from 'react';
AddButton  есть у  Зои

2021-06-29 11:40 UTC, Rostyslav-Zahorulko requested changes

2021-06-29 11:40 UTC, Rostyslav-Zahorulko commented on src/components/SprintsList/SprintList.module.css
> +.sprint_list {
Помилка в назві файлу (не вистачає `s` в слові `Sprints`). Переназви на `SprintsList.module.css`.

2021-06-29 11:40 UTC, Rostyslav-Zahorulko commented on src/components/SprintsList/SprintsList.js
> +import styles from './SprintList.module.css';
Не забудь переназвати файл стилів у імпорті.

2021-06-29 11:40 UTC, Rostyslav-Zahorulko commented on src/pages/SprintsPage/SprintsPage.js
> +      <p className={styles.sprint_desc}>
Це опис проекту, не спринта, тому клас має називатися `project_desc`.

2021-06-29 11:40 UTC, Rostyslav-Zahorulko commented on src/pages/SprintsPage/SprintsPage.js
> +        <h1 className={styles.title}> Project1</h1>
Це заголовок проекту. Назви клас `project_title`.

2021-06-29 11:40 UTC, Rostyslav-Zahorulko commented on src/pages/SprintsPage/SprintsPage.js
> +        aria-label="add"
`aria-label="add-sprint"`.

2021-06-29 11:40 UTC, Rostyslav-Zahorulko commented on src/pages/SprintsPage/SprintsPage.js
> +        <AddIcon width="44" hanging="44" fill="#fff" />
Що за `hanging`? Може, `height`?

2021-06-29 11:40 UTC, Rostyslav-Zahorulko commented on src/pages/SprintsPage/SprintsPage.js
> +    <div className={styles.sprint}>
Ніяк не зрозумію, що то за два діва - `sprint` і `sprint_title`?!

2021-06-29 11:40 UTC, Rostyslav-Zahorulko commented on src/pages/SprintsPage/Sprints.module.css
> +.sprint {
Не забудь поміняти імена класів, які зміниш у js файлі. Дивись наступний коментар.

2021-06-29 12:36 UTC, Rostyslav-Zahorulko approved these changes

2021-06-29 12:38 UTC, merged